# Generated by Django 4.2.6 on 2023-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=models.ImageField(upload_to='logo/img', verbose_name='logotype'),
        ),
    ]
