# Generated by Django 4.2.6 on 2023-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='style_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='style_name',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=10, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='color',
            field=models.CharField(default='', max_length=10, verbose_name='color'),
        ),
    ]
