# Generated by Django 4.2.6 on 2023-11-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Собственный IT-продукт', 'Собственный IT-продукт'), ('Заказная разработка', 'Заказная разработка'), ('Другое', 'Другое'), ('Неопределенный', 'Неопределенный')], max_length=100, verbose_name='category_name')),
                ('style_name', models.CharField(default='', max_length=100, verbose_name='style_name')),
                ('description', models.TextField(default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'CompanyCategory',
                'verbose_name_plural': 'CompanyCategories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(choices=[('Стартапы с IT решениями', 'Стартапы с IT решениями'), ('Сопровождение популярных массовых ИТ продуктов', 'Сопровождение популярных массовых ИТ продуктов'), ('Веб-студии', 'Веб-студии'), ('Большие ИТ - компании', 'Большие ИТ - компании'), ('B2G', 'B2G'), ('Разработка игр', 'Разработка игр'), ('Неопределенный', 'Неопределенный')], max_length=100, verbose_name='subcategory_name')),
                ('style_name', models.CharField(default='', max_length=100, verbose_name='style_name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('company_category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.category')),
            ],
            options={
                'verbose_name': 'CompanySubcategory',
                'verbose_name_plural': 'CompanySubcategories',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.AddField(
            model_name='companycategory',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.DeleteModel(
            name='CompanySubcategory',
        ),
        migrations.AddField(
            model_name='companycategory',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.category'),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='subcategory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='companycategory',
            unique_together={('subcategory_id', 'company_id')},
        ),
        migrations.RemoveField(
            model_name='companycategory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='companycategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companycategory',
            name='style_name',
        ),
    ]
