# Generated by Django 4.2.6 on 2023-11-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_logotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=models.ImageField(upload_to='companies/logo/img', verbose_name='logotype'),
        ),
    ]
