# Generated by Django 4.2.6 on 2023-11-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_category_subcategory_remove_company_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='companycategory',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companycategory',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='company_category_id',
            new_name='company_category',
        ),
    ]
