# Generated by Django 4.2.6 on 2023-12-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_category_style_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='gray', max_length=10, verbose_name='color'),
        ),
    ]
