# Generated by Django 4.2.6 on 2024-02-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_tag_companytag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
