# Generated by Django 4.2.6 on 2024-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_tag_name_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinate_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='coordinate_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
