# Generated by Django 4.2.6 on 2023-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(default=12, max_length=200, verbose_name='url'),
            preserve_default=False,
        ),
    ]
