# Generated by Django 4.2.6 on 2023-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('заказная разработка', 'Заказная разработка'), ('собственный IT-продукт', 'Собственный IT-продукт'), ('госструктуры', 'Госструктуры')], max_length=100, verbose_name='type_name')),
            ],
            options={
                'verbose_name': 'CompanyType',
                'verbose_name_plural': 'CompaniesTypes',
            },
        ),
    ]
