# Generated by Django 4.2.6 on 2023-12-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_category_color_alter_subcategory_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('home_number', models.CharField(max_length=15, verbose_name='home_number')),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(choices=[('Стартапы с IT решениями', 'Стартапы с IT решениями'), ('Сопровождение популярных массовых ИТ продуктов', 'Сопровождение популярных массовых ИТ продуктов'), ('Веб-студии', 'Веб-студии'), ('Большие ИТ - компании', 'Большие ИТ - компании'), ('B2G', 'B2G'), ('Разработка игр', 'Разработка игр'), ('Компьютерная безопасность', 'Компьютерная безопасность'), ('Неопределенный', 'Неопределенный')], max_length=100, verbose_name='subcategory_name'),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.address')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.city')),
            ],
            options={
                'verbose_name': 'CompanyAddress',
                'verbose_name_plural': 'CompanyAddresses',
            },
        ),
    ]
