# Generated by Django 4.2.6 on 2023-11-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'CompanyType', 'verbose_name_plural': 'CompanyTypes'},
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companytype'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='type_name',
            field=models.CharField(choices=[('заказная разработка', 'Заказная разработка'), ('собственный IT-продукт', 'Собственный IT-продукт'), ('госструктуры', 'Госструктуры'), ('неопределенный', 'Неопределенный')], max_length=100, verbose_name='type_name'),
        ),
    ]
