# Generated by Django 4.2.6 on 2023-12-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_address_city_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.city'),
        ),
    ]
