# Generated by Django 4.2.6 on 2023-12-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='сompany',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.company'),
        ),
    ]
