# Generated by Django 4.2.6 on 2023-11-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_url'),
        ('companies', '0006_companytype_description'),
    ]

    operations = [
    ]
