# Generated by Django 4.2.6 on 2023-11-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_merge_0004_company_url_0006_companytype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='style_name',
            field=models.CharField(default='', max_length=100, verbose_name='style_name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.companytype'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='description',
            field=models.TextField(default='', max_length=350, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='type_name',
            field=models.CharField(choices=[('Заказная разработка', 'Заказная разработка'), ('Собственный IT-продукт', 'Собственный IT-продукт'), ('Госструктуры', 'Госструктуры'), ('Разработка игр', 'Разработка игр'), ('Неопределенный', 'Неопределенный')], max_length=100, verbose_name='type_name'),
        ),
    ]
