# Generated by Django 4.2.6 on 2023-12-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_companyaddress_city_companyaddress_сompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='сompany',
            new_name='company',
        ),
    ]
