# Generated by Django 4.2.6 on 2023-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logotype',
            field=models.ImageField(upload_to='../main/static/main/img/', verbose_name='logotype'),
        ),
    ]
